CREATE OR REPLACE TRIGGER NAPTAR 
AFTER INSERT ON users 
FOR EACH ROW
BEGIN
  INSERT INTO calendars(calendar_id, user_id, name, color) VALUES (CALENDAR_SEQ.NEXTVAL, :NEW.user_id, CALENDAR_SEQ.NEXTVAL, '#6EC1F4');
END;